stages:
  - build
  - test
  - lint
  - deploy
  - cleanup

before_script:
  - echo "$ENV_NON_DEV" > .env-non-dev
  - powershell -command "Get-Content -Encoding Unicode .env-non-dev | Out-File -Encoding utf8 .env-non-dev.utf8"
  - powershell -command "Move-Item -Force .env-non-dev.utf8 .env-non-dev"

after_script:
  - rm -Fo .env-non-dev

#build-job:
#  stage: build
#  script:
#    - docker build -t daily_planner_image .
#
#test-job:
#  stage: test
#  script:
#    - docker compose run -e MODE=TEST --rm daily_planner_image pytest -s -v
#
#lint-job:
#  stage: lint
#  script:
#    - docker run -d daily_planner_image
#    - echo "Проверка форматирования с помощью black..."
#    - docker exec -it daily_planner black --config .black --check .
#    - echo "Статическая проверка типов с помощью pyright..."
#    - docker compose exec -it daily_planner pyright .
#    - echo  "Запуск flake8..."
#    - docker compose exec -it daily_planner flake8 .
#    - echo "Проверка порядка импортов с помощью isort..."
#    - docker compose exec -it daily_planner isort --check-only .
#    - docker stop daily_planner_image
#    - docker rm daily_planner_image
#
#deploy-job:
#  stage: deploy
#  script:
#    - docker compose up -d
#
#cleanup-job:
#  stage: cleanup
#  script: docker compose down
#
build-job:
  stage: build
  script:
    - docker compose build

unit-test-job:
  stage: test
  script:
    - echo "Начало тестирования"
    - docker compose run -e MODE=TEST --rm daily_planner pytest -s -v

lint-test-job:
  stage: lint
  script:
    - docker compose run -d daily_planner
    - echo "Проверка форматирования с помощью black..."
    - docker compose exec -it daily_planner black --config .black --check .
    - echo "Статическая проверка типов с помощью pyright..."
    - docker compose exec -it daily_planner pyright .
    - echo  "Запуск flake8..."
    - docker compose exec -it daily_planner flake8 .
    - echo "Проверка порядка импортов с помощью isort..."
    - docker compose exec -it daily_planner isort --check-only .
    - docker compose stop daily_planner
    - docker compose rm daily_planner

deploy-job:
  stage: deploy
  script:
    - docker compose up -d

cleanup-job:
  stage: cleanup
  script:
    - docker compose down