services:
  db:
    image: postgres:17
    container_name: daily_planner_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432
    volumes:
      - fastapi_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.1.1-management
    container_name: daily_planner_rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    hostname: rabbitmq
    env_file:
      - .env-non-dev
    ports:
      - 5672:5672
      - 15672:15672

  daily_planner:
    image: daily_planner_image
    build:
      context: .
    container_name: daily_planner_app
    restart: always
    env_file:
      - .env-non-dev
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: [ "/daily_planner/docker/app.sh" ]
    ports:
      - 7777:8000

  celery:
    image: daily_planner_celery_image
    build:
      context: .
    container_name: daily_planner_celery
    restart: always
    env_file:
      - .env-non-dev
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: [ "/daily_planner/docker/celery.sh", "celery" ]

  flower:
    image: daily_planner_flower_image
    build:
      context: .
    container_name: daily_planner_flower
    restart: always
    env_file:
      - .env-non-dev
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: [ "/daily_planner/docker/celery.sh", "flower" ]
    ports:
      - 5555:5555

volumes:
  fastapi_postgres_data: