services:
  db:
    image: postgres:17
    container_name: daily_planner_db
    env_file:
      - .env-non-dev
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 5432:5432
    volumes:
      - fastapi_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.1.1-management
    container_name: daily_planner_rabbitmq
    #env_file:
    #  - .env-non-dev
    environment:
      #RABBIT_USER: "${RABBIT_USER}"
      #RABBIT_PASS: "${RABBIT_PASS}"
      #RABBIT_HOST: "${RABBIT_HOST}"
      #RABBIT_PORT: "${RABBIT_PORT}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  daily_planner:
    image: daily_planner_image:latest
    build:
      context: .
    container_name: daily_planner_app
    env_file:
      - .env-non-dev
    restart: always
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: [ "bash", "/daily_planner/docker/app.sh" ]
    ports:
      - 7777:8000

  celery:
    image: daily_planner_celery_image
    build:
      context: .
    container_name: daily_planner_celery
    env_file:
      - .env-non-dev
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: [ "bash", "/daily_planner/docker/celery.sh", "celery" ]

  flower:
    image: daily_planner_flower_image
    build:
      context: .
    container_name: daily_planner_flower
    env_file:
      - .env-non-dev
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: [ "bash", "/daily_planner/docker/celery.sh", "flower" ]
    ports:
      - 5555:5555

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    privileged: true

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafanadata:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3001:3000

volumes:
  fastapi_postgres_data:
  grafanadata:
  prometheusdata: