{
 "title": "FastAPI Дашборд - Приложение-ежедневник",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Запросов в минуту",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Количество ошибок (30 сек)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=\"500\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Использование памяти",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"daily_planner\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "Среднее время ответа",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"daily_planner\",handler!=\"none\"} / http_request_duration_seconds_count",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Запросы < 100 ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{le=\"0.1\"}[1m]) \n/ ignoring (le) increase(http_request_duration_seconds_count[1m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Использование CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"daily_planner\"}[30s])",
     "legendFormat": "cpu"
    }
   ]
  }
 ]
}