"""empty message

Revision ID: 0eb56900ff44
Revises: e1e765f17db3
Create Date: 2025-06-10 20:12:18.719246

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "0eb56900ff44"
down_revision: Union[str, None] = "e1e765f17db3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="statusenum",
        new_values=["WORK", "READY", "EXPIRED", "WAITING"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="entries",
                column_name="status",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="statusenum",
        new_values=["WORK", "READY", "EXPIRED"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="entries",
                column_name="status",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
